FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get -y install gcc libpq-dev 

WORKDIR /app

COPY requirments.txt /app/requirments.txt

RUN pip install -r /app/requirments.txt


COPY . /app/